// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAILGYUfwcL4m0wpdfPxan2DVu4E2OcbPw',
    appId: '1:816665846900:web:423603dcf5fe2f60741d21',
    messagingSenderId: '816665846900',
    projectId: 'kitty-community-app-datn20231',
    authDomain: 'kitty-community-app-datn20231.firebaseapp.com',
    databaseURL: 'https://kitty-community-app-datn20231-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitty-community-app-datn20231.appspot.com',
    measurementId: 'G-N9RN1789FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzELTH0uazmaXd9mFToSp9jkwto2Nx920',
    appId: '1:816665846900:android:5b94df3f974701cd741d21',
    messagingSenderId: '816665846900',
    projectId: 'kitty-community-app-datn20231',
    databaseURL: 'https://kitty-community-app-datn20231-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitty-community-app-datn20231.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2PfDL1RggpABj5ZWGMj99HXE3VuFfPM',
    appId: '1:816665846900:ios:fd2d92dd5e88c120741d21',
    messagingSenderId: '816665846900',
    projectId: 'kitty-community-app-datn20231',
    databaseURL: 'https://kitty-community-app-datn20231-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitty-community-app-datn20231.appspot.com',
    iosClientId: '816665846900-0vbjf0ukgt42t57cnqghd1oil1uf6q2r.apps.googleusercontent.com',
    iosBundleId: 'com.hust.datn.kittyCommunityApp',
  );
}
