name: kitty_community_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

  # local storage
  hive: ^2.2.3    # for save and get data quickly
  hive_flutter: ^1.1.0

  # for biometric login
  local_auth: ^2.1.5

  # for cache network image
  cached_network_image: ^3.2.1

  # for set up firebase & notification
  firebase_messaging: ^14.6.2
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  cloud_firestore: ^4.8.1
  flutter_local_notifications: ^14.1.1

  # for format data, get locale
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  # provide Either datatype return
  dartz: ^0.10.1

  # for check internet connection
  connectivity_plus: ^4.0.1

  # for pickimage from gallery or camera
  image_picker: ^0.8.7+5

  # for load image .svg
  flutter_svg: ^2.0.5

  # for loading
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  # for launch web url
  url_launcher: ^6.1.11

  # comp
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  auto_size_text: ^3.0.0
  data_table_2: ^2.4.2
  rive: ^0.11.4
  flex_color_scheme: ^7.0.5
  sizer: ^2.0.15


  # get app info
  package_info_plus: ^4.0.2
  store_redirect: ^2.0.1
  permission_handler: ^10.4.3

dev_dependencies: 
  flutter_lints: 2.0.3
  logger: ^1.1.0
  flutter_test: 
    sdk: flutter
  
  # for generate code
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.13.1"

flutter: 
  uses-material-design: true

  assets:
      - assets/icons/
      - assets/images/
      - assets/rive/

